services:
  - type: web
    name: shree-giriraj-erp
    env: docker
    dockerfilePath: ./laravel/Dockerfile
    dockerContext: ./laravel
    plan: free
    region: singapore
    envVars:
      - key: APP_NAME
        value: "Shree Giriraj Poly Plast"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /var/www/html/database/database.sqlite
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
