name: shreegiriraj_erp
description: "Shree Giriraj Poly Plast - ERP Mobile App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  url_launcher: ^6.3.1
  cached_network_image: ^3.4.1
  flutter_slidable: ^3.1.1
  shimmer: ^3.0.0
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
